
ingressHost: wa-chart-release.service.core-compute-preview.internal
ingressIP: "10.97.17.51"
consulIP: "10.97.11.254"

readinessDelay: 90
livenessDelay: 90

global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  postgresHost: "chart-tests-flexibleserver-postgres-preview.postgres.database.azure.com"
  postgresSecret: chart-test-postgres-password
  databaseNamePrefix: "chart-test-"
wa:
  servicebus:
    enabled: true
  postgresql:
    enabled: true

servicebus:
  tags:
    teamName: "Work Allocation"
    applicationName: "event handler"
    builtFrom: "https://github.com/hmcts/wa-chart"
    businessArea: "CFT"
    environment: "development"
  enabled: true
  resourceGroup: chart-tests-aso-preview-rg
  sbNamespace: chart-tests-servicebus
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
        requiresSession: true

wa-case-event-handler:
  java:
    environment:
      CCD_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
      CCD_SEARCH_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal

wa-task-management-api:
  java:
    environment:
      CCD_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal

wa-task-monitor:
  java:
    environment:
      CCD_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
      CCD_SEARCH_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal

wa-workflow-api:
  java:
    environment:
      DB_READER_USERNAME: "hmcts"

postgresql:
  flexibleserver: chart-tests-flexibleserver-postgres-preview
  setup:
    databases:
      - name: "{{ .Values.global.databaseNamePrefix }}cft_task_db"
      - name: "{{ .Values.global.databaseNamePrefix }}wa-case-event-handler"
      - name: "{{ .Values.global.databaseNamePrefix }}wa_workflow_api"
      - name: "{{ .Values.global.databaseNamePrefix }}camunda"
