
ingressHost: wa-chart-release.service.core-compute-preview.internal
ingressIP: "10.97.17.51"
consulIP: "10.97.11.254"

readinessDelay: 90
livenessDelay: 90

global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

wa:
  servicebus:
    enabled: true
  postgresql:
    enabled: false

servicebus:
  tags:
    teamName: "Work Allocation"
    applicationName: "event handler"
    builtFrom: "https://github.com/hmcts/wa-chart"
    businessArea: "CFT"
    environment: "development"
  enabled: true
  resourceGroup: chart-servicebus-test
  serviceplan: standard
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes

