
ingressHost: wa-chart-release.service.core-compute-preview.internal
ingressIP: "10.97.17.51"
consulIP: "10.97.11.254"

readinessDelay: 90
livenessDelay: 90

global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

wa:
  servicebus:
    enabled: true
  postgresql:
    enabled: false

