apiVersion: v2
description: A Helm chart for the Work Allocation product.
name: wa
# Static chart version, as uses tag
version: 0.1.0 # Do not change
keywords:
  - wa
  - work allocation
dependencies:
  - name: wa-task-management-api
    version: ~0.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.taskManagement.enabled
  - name: wa-task-monitor
    version: ~0.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.taskMonitor.enabled
  - name: wa-case-event-handler
    version: ~0.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.eventHandler.enabled
  - name: wa-workflow-api
    version: ~0.1.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.workflow.enabled
  - name: wa-task-batch-service
    version: ~0.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    alias: wa-initiation-batch
    condition: wa.taskBatchCron.enabled
  - name: wa-task-batch-service
    version: ~0.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    alias: wa-reconfiguration-batch
    condition: wa.reconfigurationBatchCron.enabled
  - name: wa-task-batch-service
    version: ~0.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    alias: wa-termination-batch
    condition: wa.terminationBatchCron.enabled
  - name: wa-message-cron-service
    version: ~0.0.15
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.messageCron.enabled
  - name: camunda-bpm
    version: 0.0.48
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.camunda.enabled
  - name: postgresql
    version: 1.1.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.postgresql.enabled
  - name: servicebus
    version: 1.2.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
    condition: wa.servicebus.enabled
