tags:
  wa: true

#subcharts conditions
wa:
  taskManagement:
    enabled: true
  taskMonitor:
    enabled: true
  eventHandler:
    enabled: true
  workflow:
    enabled: true
  taskBatchCron:
    enabled: true
  messageCron:
    enabled: true
  camunda:
    enabled: true
  postgresql:
    enabled: true
  servicebus:
    enabled: false
  reconfigurationBatchCron:
    enabled: true
  terminationBatchCron:
    enabled: true
global:
  postgresUsername: hmcts
  postgresHost: ""
  postgresSecret: ""
  environment: aat

wa-task-management-api:
  java:
    releaseNameOverride: "{{ .Release.Name }}-wa-task-management-api"
    ingressHost: ""
    keyVaults:
      wa:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string
          - name: wa-system-username
            alias: WA_SYSTEM_USERNAME
          - name: wa-system-password
            alias: WA_SYSTEM_PASSWORD
          - name: wa-idam-client-secret
            alias: WA_IDAM_CLIENT_SECRET
          - name: s2s-secret-task-management-api
            alias: S2S_SECRET_TASK_MANAGEMENT_API
          - name: ld-secret
            alias: LAUNCH_DARKLY_SDK_KEY
    environment:
      CAMUNDA_URL: http://{{ .Release.Name }}-camunda/engine-rest
      ROLE_ASSIGNMENT_URL: http://{{ .Release.Name }}-am-role-assignment-service
      POSTGRES_NAME: cft-task-db
      POSTGRES_HOST: '{{ tpl .Values.global.postgresHost $}}'
      POSTGRES_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
      POSTGRES_CONNECTION_OPTIONS: "?currentSchema=cft_task_db&stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      CCD_URL: http://{{ .Release.Name }}-ccd-data-store-api
    secrets:
      POSTGRES_PASSWORD:
        secretRef: "{{ .Values.global.postgresSecret }}"
        key: PASSWORD
        disabled: false

wa-task-monitor:
  java:
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-wa-task-monitor"
    keyVaults:
      wa:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string
          - name: s2s-secret-task-monitor
            alias: S2S_SECRET_TASK_MONITOR
          - name: wa-system-username
            alias: WA_SYSTEM_USERNAME
          - name: wa-system-password
            alias: WA_SYSTEM_PASSWORD
          - name: wa-idam-client-secret
            alias: WA_IDAM_CLIENT_SECRET
    environment:
      CAMUNDA_URL: http://{{ .Release.Name }}-camunda/engine-rest
      TASK_MANAGEMENT_SERVICE_URL: http://{{ .Release.Name }}-wa-task-management-api
      CASE_EVENT_HANDLER_SERVICE_URL: http://{{ .Release.Name }}-wa-case-event-handler
      CCD_SEARCH_URL: http://{{ .Release.Name }}-ccd-data-store-api
      CCD_URL: http://{{ .Release.Name }}-ccd-data-store-api
      ROLE_ASSIGNMENT_URL: http://{{ .Release.Name }}-am-role-assignment-service

wa-case-event-handler:
  java:
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-wa-case-event-handler"
    secrets:
      AZURE_SERVICE_BUS_CONNECTION_STRING:
        secretRef: servicebus-access
        key: connectionString
      POSTGRES_PASSWORD:
        secretRef: "{{ .Values.global.postgresSecret }}"
        key: PASSWORD
        disabled: false
    keyVaults:
      wa:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string
          - name: s2s-secret-case-event-handler
            alias: S2S_SECRET_CASE_EVENT_HANDLER
          - name: ld-secret
            alias: LAUNCH_DARKLY_SDK_KEY
          - name: wa-idam-client-secret
            alias: WA_IDAM_CLIENT_SECRET
    environment:
      CAMUNDA_URL: http://{{ .Release.Name }}-camunda/engine-rest
      CCD_URL: http://{{ .Release.Name }}-ccd-data-store-api
      CCD_SEARCH_URL: http://{{ .Release.Name }}-ccd-data-store-api
      ROLE_ASSIGNMENT_URL: http://{{ .Release.Name }}-am-role-assignment-service
      WA_WORKFLOW_API_URL: http://{{ .Release.Name }}-wa-workflow-api
      WA_TASK_MANAGEMENT_API_URL: http://{{ .Release.Name }}-wa-task-management-api
      AZURE_SERVICE_BUS_TOPIC_NAME: "{{ .Release.Name }}-servicebus-ccd-case-events"
      AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: "{{ .Release.Name }}-servicebus-ccd-case-events"
      AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: "{{ .Release.Name }}-servicebus-ccd-case-events"
      POSTGRES_NAME: wa-case-event-handler
      POSTGRES_HOST: '{{ tpl .Values.global.postgresHost $}}'
      POSTGRES_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
      POSTGRES_CONNECTION_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      RECEIVED_MESSAGE_HEALTH_CHECK: disabled

wa-workflow-api:
  java:
    ingressHost: ""
    releaseNameOverride: "{{ .Release.Name }}-wa-workflow-api"
    secrets:
      POSTGRES_PASSWORD:
        secretRef: "{{ .Values.global.postgresSecret }}"
        key: PASSWORD
        disabled: false
    keyVaults:
      wa:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string
          - name: s2s-secret-workflow-api
            alias: S2S_SECRET_WORKFLOW_API
          - name: ld-secret
            alias: LAUNCH_DARKLY_SDK_KEY
    environment:
      CAMUNDA_URL: http://{{ .Release.Name }}-camunda/engine-rest
      POSTGRES_NAME: wa-workflow-api
      POSTGRES_HOST: '{{ tpl .Values.global.postgresHost $}}'
      POSTGRES_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
      POSTGRES_CONNECTION_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      TASK_MANAGEMENT_URL: http://{{ .Release.Name }}-wa-task-management-api

wa-message-cron-service:
  job:
    releaseNameOverride: "{{ .Release.Name }}-wa-message-cron-service"
    kind: CronJob
    schedule: "*/5 * * * *"
    aadIdentityName: wa
    keyVaults:
      wa:
        secrets:
          - s2s-secret-case-event-handler
    environment:
      WA_CASE_EVENT_HANDLER_SERVICE_URL: http://{{ .Release.Name }}-wa-case-event-handler

wa-initiation-batch:
  job:
    releaseNameOverride: "{{ .Release.Name }}-wa-task-batch-initiation"
    kind: CronJob
    schedule: "*/5 * * * *"
    aadIdentityName: wa
    keyVaults:
      wa:
        secrets:
          - s2s-secret-task-monitor
    environment:
      S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
      S2S_MICROSERVICE_NAME_TASK_MONITOR: "wa_task_monitor"
      WA_TASK_MONITOR_SERVICE_URL: http://{{ .Release.Name }}-wa-task-monitor
      JOB_NAME: "INITIATION"
      ALLOW_CONFIG_MUTATIONS: true

wa-reconfiguration-batch:
  job:
    releaseNameOverride: "{{ .Release.Name }}-wa-task-batch-reconfiguration"
    kind: CronJob
    schedule: "*/5 * * * *"
    aadIdentityName: wa
    keyVaults:
      wa:
        secrets:
          - s2s-secret-task-monitor
    environment:
      S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
      S2S_MICROSERVICE_NAME_TASK_MONITOR: "wa_task_monitor"
      WA_TASK_MONITOR_SERVICE_URL: http://{{ .Release.Name }}-wa-task-monitor
      JOB_NAME: "RECONFIGURATION"
      ALLOW_CONFIG_MUTATIONS: true

wa-termination-batch:
  job:
    releaseNameOverride: "{{ .Release.Name }}-wa-task-batch-termination"
    kind: CronJob
    schedule: "*/5 * * * *"
    aadIdentityName: wa
    keyVaults:
      wa:
        secrets:
          - s2s-secret-task-monitor
    environment:
      S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
      S2S_MICROSERVICE_NAME_TASK_MONITOR: "wa_task_monitor"
      WA_TASK_MONITOR_SERVICE_URL: http://{{ .Release.Name }}-wa-task-monitor
      JOB_NAME: "TERMINATION"
      ALLOW_CONFIG_MUTATIONS: true

camunda-bpm:
  java:
    releaseNameOverride: "{{ .Release.Name }}-camunda"
    ingressHost: "camunda-{{ .Release.Name }}.preview.platform.hmcts.net"
    disableKeyVaults: true
    environment:
      CAMUNDA_DB_HOST: '{{ tpl .Values.global.postgresHost $}}'
      CAMUNDA_DB_USER_NAME: '{{ tpl .Values.global.postgresUsername $}}'
      CAMUNDA_DB_CONN_OPTIONS: ""
      TASK_MANAGEMENT_API_URL: http://{{ .Release.Name }}-wa-task-management-api
      CAMUNDA_BPM_DATABASE_SCHEMAUPDATE: true
      RELEASE_REVISION: "{{ .Release.Revision }}"
      CAMUNDA_API_AUTH_ENABLED: false
    secrets:
      POSTGRES_PASSWORD:
        secretRef: "{{ .Values.global.postgresSecret }}"
        key: PASSWORD
        disabled: false